version: '3.8'

services:
  backend:
    image: python:3.9
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: bash -c "yarn install && yarn start"
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  s3:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - s3_data:/data

volumes:
  db_data:
  s3_data:
